In [10]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

DATA_DIR = '../datasets/rossmann-store-sales'
STORE_FILE = os.path.join(DATA_DIR, 'store.csv')
TRAIN_FILE = os.path.join(DATA_DIR, 'train.csv')

store_df = pd.read_csv(STORE_FILE, index_col=0)
train_df = pd.read_csv(TRAIN_FILE)

C:\Users\m_kal\AppData\Local\Temp\ipykernel_4360\2054034874.py:11: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv(TRAIN_FILE)

In [12]:
train_df.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [13]:
store_df.head()

,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
Store,,,,,,,,,
1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [24]:
def date_from_week_year(row, year_col: str = "Promo2SinceYear", week_col: str = 'Promo2SinceWeek', weekday: int = 1):
    """
    Convert (year, week) to a date, handling missing values.
    Returns Monday of that ISO week by default.
    """

    if pd.isna(row[year_col]) or pd.isna(row[week_col]):
        out = pd.NaT  # Missing date

    else:
        date_str = f"{int(row[year_col])}-W{int(row[week_col]):02d}-{weekday}"
        out = pd.to_datetime(date_str, format="%G-W%V-%u")

    return out

store_df["Promo2SinceDate"] = store_df.apply(date_from_week_year, axis=1)

store_df

,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,Promo2SinceDate
Store,,,,,,,,,,
1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN,NaT
2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct",2010-03-29
3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct",2011-04-04
4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN,NaT
5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...
1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct",2013-07-29
1112,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN,NaT
1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN,NaT
1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN,NaT
1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec",2012-05-28